# Generated by Django 5.2.9 on 2025-12-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('alt', models.CharField(blank=True, null=True)),
                ('demo_link', models.CharField(blank=True, null=True)),
                ('code_link', models.CharField(blank=True, null=True)),
                ('uptade_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('techs', models.ManyToManyField(related_name='projects', to='portifolio.techs')),
            ],
        ),
    ]
